global:
  scrape_interval: 5s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["docker-backend-1:5000"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]



